### ISSUE TITLE
LA Pan

### ISSUE THREAD

**Issue by sum1won** [sum1won/summod#47]
??

**Comment by KimmoKM** [comment]
Just throwing some suggestions out there, not in any particular and I'm by no means suggesting that all of these should be implemented:
- One of the problems with Satyr Hoplites is that they can tank all right but 3 damage spear makes them ineffective against LA armour despite their superhuman strength. Suppose you gave them 5 damage weapon like pike but still usable in one hand and 5 length instead of 6? To my knowledge Macedonian Phalangites used shields with their sarissa (indeed, LA Arco Phalangites do use length 5 "long spear" with shield) so that might be the name for the new weapon, which would also help Arco. +1 morale buff wouldn't hurt either, satyrs have been fighting in formations a long time by LA and they're not unruly hordes anymore. 11 morale like Arco hoplite or even 12 morale like LA Arco phalangite would seem more appropriate.
- Satyr snipers are a cool unit both thematically and mechanically with their heavy armour and superhuman statline allowing them to win almost any archer duels... gold to gold. The thing is, their resource cost is prohibitive and you tend to be better-off with indie crossbowmen since they allow you to field twice the firepower. Either reducing the resource cost somehow or giving them something to compensate for the high resource cost (like a weapon similar to Agarthan Steel Crossbow - LA Pan might not have as good technology, but satyrs are stronger than humans and even with mechanical aids reducing the strength required to load crossbows, you'd expect to see some benefit from that) would make them a more desirable unit. If it didn't increase their cost further, a proper sidearm instead of hoof would also be nice (I don't see why crossbow satyrs would leave to battle without melee weapon while other nations bring short swords and such like).
- Reduced encumbrance on cataphracts. I know it's related how mounted units are handled in Dominions, but the warhorses of Ulm and Marignon seem to carry their barding without problem and the bottom half of centaurs is presumably just as strong (also: "and are in every way as powerful as the knights of mankind".. except that they fall asleep from exhaustion while knights are just starting). The fix would be to reduce encumbrance of centaur barding. This change probably could be done for MA Centaur Cataphracts as well, they're not really worth recruiting over Centaur Warriors. In addition, similar to the weapon choice of hoplites, light lance seems a bit flimsy for the age. Now, you obviously can't just give them lances because those are only usable once per battle, but light lances are a weapon even Caelians use in EA and I think LA "heavy cavalry" deserves something better (hoof attack scales with strength unlike human knights but otherwise centaurs actually deal less damage). One extra point of strength (to get on par with Centaur Warriors of old) would also help/do the trick.
- I really don't see the idea behind size 3 tramplers. I suppose they can do all right in some specific conditions like going after Earth Melded enemy, but in my experience they tend to be surrounded and killed or stuck against anything size 3 that they are completely ineffective against due to their low attack skill. Besides a nice price reduction, I don't know how you might address minotaurs (during all ages), but it is one possible avenue for buffing LA Pan while making EA/MA less definitely about Centaur Warriors and Revelers. Oh, and I don't see why Grove Guards are MM1, which is a rather prohibitive even if you did find a use for minotaurs.
- Make standard harpies (including the commander) and undisciplined satyrs recruitable in forest provinces. Hell, I think it would be thematic to have the satyrs confined to forest recruitment: I'd imagine Satyr Sneaks in particular (with their unrest generation) wouldn't be able to find their place in the new cities of the halfmen nation so forest recruitment would actually be thematic in this sense.
- Increase the EDNB random chance on Panii to 50% (or alternatively, if you don't think they've had Pandemoniac or Panic Apostate influences, 50% EN 10% DB). The unit description mentions their waning influence but there's no mention of them having lost their powers. If you want extra thematic justification for this change, their startage could be increased to suggest they are the last of their kind and members of the last generation that still practised the "MA era" magic.

**Comment by sum1won** [comment]
I'll be implementing some similar changes, although not quite to the same degree
